FROM debian:buster-20220711-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    perl \
    python3 \
    dos2unix \
    && rm -rf /var/lib/apt/lists/*

# Add cmake
ENV CMAKE_SHA=d25a8e8b76c137ffd55fa28b7a803309a2c6992e30fa0f1cb2172d5b970106e2
RUN curl https://github.com/Kitware/CMake/releases/download/v3.20.1/cmake-3.20.1-linux-x86_64.sh -Lo cmake.sh \
    && echo "${CMAKE_SHA} cmake.sh" | sha256sum --check --status \
    && chmod +x cmake.sh \
    && ./cmake.sh --skip-license --prefix=/usr/local \
    && rm ./cmake.sh

#Add OPKG tools
ENV OPKG_UTILS_TAR_SHA256=046517600fb0aed6c4645edefe02281f4fa2f1c02f71596152d93172452c0b01
RUN curl https://git.yoctoproject.org/cgit/cgit.cgi/opkg-utils/snapshot/opkg-utils-0.4.3.tar.gz -Lo opkg-utils.tar.gz \
    && echo "${OPKG_UTILS_TAR_SHA256} opkg-utils.tar.gz" | sha256sum --check --status \
    && mkdir /opkg-utils \
    && tar -zxf opkg-utils.tar.gz -C /opkg-utils --strip-components=1 \
    && rm opkg-utils.tar.gz \
    && cd /opkg-utils \
    && make \
    && make install \
    && cd / \
    && rm -rf /opkg-utils

#Add Boost (without ICU Locale Support)
ENV BOOST_DIR=/boost
ENV BOOST_TAR_SHA256=5347464af5b14ac54bb945dc68f1dd7c56f0dad7262816b956138fc53bcc0131
RUN curl https://sourceforge.net/projects/boost/files/boost/1.77.0/boost_1_77_0.tar.gz/download -Lo boost.tar.gz \
    && echo "${BOOST_TAR_SHA256} boost.tar.gz" | sha256sum --check --status \
    && mkdir $BOOST_DIR \
    && tar -zxf boost.tar.gz -C $BOOST_DIR --strip-components=1 \
    && rm boost.tar.gz \
    && cd $BOOST_DIR \
    && ./bootstrap.sh --without-icu
    

# Download and Install the cross compile toolchain for x64 targets
ENV TOOLCHAIN_x64_SHA=c3c4ccf96cc14daea9f350db326b471f817d32740d3b39a3641e7d1cd8056a93
RUN curl https://download.ni.com/support/softlib/labview/labview_rt/2018/Linux%20Toolchains/linux/oecore-x86_64-core2-64-toolchain-6.0.sh -Lo install-tc.sh \
    && echo "${TOOLCHAIN_x64_SHA} install-tc.sh" | sha256sum --check --status \
    && chmod +x ./install-tc.sh \
    && ./install-tc.sh -y \
    && rm ./install-tc.sh

ENV NILRT_SDK_CROSS_COMPILE_x64_SETUP=/usr/local/oecore-x86_64/environment-setup-core2-64-nilrt-linux

# Copy Cross-Compile Config for boost
COPY user-config-x64.jam $BOOST_DIR/tools/build/src/user-config.jam

# Copy and run dependency booststrap script
COPY bootstrap.sh /
RUN dos2unix /bootstrap.sh && chmod +x /bootstrap.sh && /bootstrap.sh

# Copy opkg-package file tree
COPY opkg-package-x64 /opkg-package
ENV OPKG_PKG_BUILD_DIR=/opkg-package

# Copy build and package script
COPY build-and-package.sh /
RUN dos2unix /build-and-package.sh

# Set entrypoint to execute build script
ENTRYPOINT ["/bin/bash", "/build-and-package.sh"]